import java.util.Scanner;

public class MicrowaveCooking {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        // Prompt user for the type of food (sub, pizza, or soup)
        System.out.print("Are you heating sub, pizza, or soup?: ");
        String subPizzaOrSoup = scanner.nextLine();

        // Prompt user for the number of items to cook
        System.out.print("How many " + subPizzaOrSoup + "(s) are you cooking? (max: 3): ");
        int numberOfFood = Integer.parseInt(scanner.nextLine());

        // Process
        int minute = 0;
        int second = 0;

        if (subPizzaOrSoup.equals("sub")) {
		if (numberOfFood == 1) {
			minute = 1;
			second = 0;
		} else if (numberOfFood == 2) {
			minute = 1;
			second = 30;
		} else if (numberOfFood == 3) {
			minute = 2;
			second = 0;
		} else {
			System.out.println("Invalid input");
			return;
		}
	} else if (subPizzaOrSoup.equals("pizza")) {
		if (numberOfFood == 1) {
			minute = 0;
			second = 45;
		} else if (numberOfFood == 2) {
			minute = 1;
			second = 8;
		} else if (numberOfFood == 3) {
			minute = 1;
			second = 20;
				    //                                                                                                                                                                                                                                                                                                                                                                                                                             } else {
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                             System.out.println("Invalid input");
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                                             return;
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 } else if (subPizzaOrSoup.equals("soup")) {
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if (numberOfFood == 1) {
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             minute = 1;
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             second = 45;
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         } else if (numberOfFood == 2) {
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         minute = 2;
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         second = 18;
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     } else if (numberOfFood == 3) {
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     minute = 3;
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     second = 20;
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 } else {
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 System.out.println("Invalid input");
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return;
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     } else {
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 System.out.println("Invalid Input");
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return;
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
				    //
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // Output
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     System.out.println("The total cook time is " + minute + " minutes and " + second + " seconds.\n");
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             System.out.println("Done.");
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
				    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
				    //
